server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jobs
    driver-class-name: org.mariadb.jdbc.Driver
    username: jobsmatch
    password: 1234

  session:
    store-type: none

  
  # jpa:
  #   open-in-view: false
  #   hibernate:
  #     ddl-auto: create
      
    # properties:
    #   '[hibernate.format_sql]': true    
  output:
    ansi:
      enabled: always

logging:
  level:
    '[org.springframework.boot.web]': INFO
    #'[org.springframework.web]': DEBUG
    


